name: Autumn
options:
  bundleIdPrefix: DART-Meadow-LLC
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.4"
  xcodeCompatibilityVersion: "Xcode 14.0"
  generateEmptyDirectories: true
packages:
  swift-markdown-ui:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    from: "2.4.0"
targets:
  AutumnApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - Sources/AutumnApp
      - Sources/AutumnServices
      - Sources/LEATRCore
    info:
      path: Sources/AutumnApp/Info.plist
    entitlements:
      path: Sources/AutumnApp/AutumnApp.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: DART-Meadow-LLC.Autumn
        DEVELOPMENT_TEAM: L7AHWS9Q6V
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "5.9"
        CODE_SIGN_ENTITLEMENTS: Sources/AutumnApp/AutumnApp.entitlements
    dependencies:
      - package: swift-markdown-ui
        product: MarkdownUI
