name: Autumn
options:
  bundleIdPrefix: com.dartmeadow
  deploymentTarget:
    iOS: "16.0"
  generateEmptyDirectories: true
packages:
  swift-markdown-ui:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    from: "2.4.0"
targets:
  AutumnApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - Sources/AutumnApp
      - Sources/AutumnServices
      - Sources/LEATRCore
    info:
      path: Sources/AutumnApp/Info.plist
    entitlements:
      path: Sources/AutumnApp/AutumnApp.entitlements
    settings:
      base:
        PRODUCT_NAME: Autumn
        PRODUCT_BUNDLE_IDENTIFIER: com.dartmeadow.autumn
        DEVELOPMENT_TEAM: L7AHWS9Q6V
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "5.10"
        CODE_SIGN_ENTITLEMENTS: Sources/AutumnApp/AutumnApp.entitlements
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        TARGETED_DEVICE_FAMILY: "1,2"
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
    dependencies:
      - package: swift-markdown-ui
        product: MarkdownUI
schemes:
  AutumnApp:
    build:
      targets:
        AutumnApp: all
    archive:
      config: Release
