import Foundation
import LEATRCore
import AutumnServices

/// TF161: the live feed is a genuinely separate concern from the manual
/// export built earlier — its own master maze, its own chunked directory,
/// and (this is the real constraint worth being upfront about) no
/// server-side always-on process exists here, because there isn't one:
/// the data itself only ever gets generated by whichever device's app is
/// actually open and processing reflexes. "Always running" in practice
/// means every active session checks a shared, GAS-persisted flag and
/// contributes to the same chunk stream when it's on — matching exactly
/// what was described: if nobody has the app open, there's genuinely
/// nothing to collect, and the first person who signs in makes the
/// journal active again.
@MainActor
public final class LiveFeedController: ObservableObject {
    public static let shared = LiveFeedController()

    // TF164: the actual root cause of "still toggling off," found by
    // checking the real repo directly — ashtree/analytics-live/ didn't
    // exist at all. Every write had been failing. Traced into presence.gs
    // itself: ashWrite() always returns {ok: true} regardless of whether
    // the underlying _ashWrite() succeeded, and _ashWrite() wraps its own
    // GitHub PUT in a bare try/catch that discards the fetch result and
    // swallows any exception silently — a write can fail for any reason
    // (including GitHub's rate limiting) with zero indication anywhere.
    // This app's own code was firing a write on every single reflex event
    // — a single message-processing cycle fires stage/tool/math/emotion
    // in quick succession, each one immediately triggering both a chunk
    // append AND a live-export replace. That's easily 8+ rapid writes to
    // the same repo per message, which is exactly the kind of pattern
    // GitHub's secondary rate limits exist to catch — and with the GAS
    // side unable to report that failure, it looked indistinguishable
    // from the toggle itself being flaky. Not touching presence.gs itself
    // here (a shared script many other features depend on; not a change
    // to make blind), fixing it at the actual source instead: batching
    // writes on a timer instead of firing one per event.
    @Published public private(set) var isEnabled = true
    @Published public private(set) var masterMaze: LEMACEngineASH.CubicResult?
    @Published public private(set) var masterMazeWidth = 10
    @Published public private(set) var masterMazeHeight = 10
    @Published public private(set) var masterMazeDepth = 10
    @Published public private(set) var masterMazeId: String = ""
    @Published public private(set) var currentChunkIndex = 0
    @Published public private(set) var currentChunkBytes = 0
    @Published public var statusText = ""

    private let chunkCapBytes = 5 * 1024 * 1024   // 5 MB per chunk, per direct spec
    private let configPath = "ashtree/analytics-live/config.json"
    private var pendingChunkEvents: [[String: Any]] = []
    private var refreshTimer: Timer?
    private var flushTimer: Timer?
    private var didInitializeRemote = false
    // TF162: within a settle window after our OWN write, a remote read is
    // more likely to be a stale echo of the pre-write state than genuinely
    // newer information.
    private var lastLocalWriteTime: Date?
    private let writeSettleWindow: TimeInterval = 90
    private var observers: [NSObjectProtocol] = []

    private init() {
        Task { await refreshFromRemote() }
        // Poll the shared flag periodically rather than only on launch —
        // any session should pick up an admin's toggle without needing a
        // relaunch.
        refreshTimer = Timer.scheduledTimer(withTimeInterval: 30, repeats: true) { [weak self] _ in
            Task { await self?.refreshFromRemote() }
        }
        // TF164: batches every event this session records and writes at
        // most once per interval, drastically cutting write frequency
        // instead of firing one GitHub commit per reflex event.
        flushTimer = Timer.scheduledTimer(withTimeInterval: 8, repeats: true) { [weak self] _ in
            Task { await self?.flushIfNeeded() }
        }
        subscribeToAnalyticsEvents()
    }

    // MARK: — Admin control (the toggle in AnalyticsExportPanel)

    /// TF164: per direct instruction, this should already be active the
    /// moment the admin console opens — the toggle's real job is letting
    /// the admin STOP an already-running feed and RESUME it, not start
    /// from an off-by-default state. A brand new master maze only gets
    /// generated here if none exists yet at all (the very first time
    /// anyone has ever enabled this); resuming after a stop reuses
    /// whatever maze and chunk position was already in progress.
    public func setEnabled(_ on: Bool) async {
        if on && masterMaze == nil {
            generateMasterMaze(width: masterMazeWidth, height: masterMazeHeight, depth: masterMazeDepth)
        }
        isEnabled = on
        await writeConfig()
    }

    public func regenerateMasterMaze(width: Int, height: Int, depth: Int) async {
        generateMasterMaze(width: width, height: height, depth: depth)
        currentChunkIndex = 0
        currentChunkBytes = 0
        pendingChunkEvents = []
        await writeConfig()
    }

    private func generateMasterMaze(width w: Int, height h: Int, depth d: Int) {
        let cw = min(max(w, AnalyticsExportMaze.minDimension), AnalyticsExportMaze.maxDimension)
        let ch = min(max(h, AnalyticsExportMaze.minDimension), AnalyticsExportMaze.maxDimension)
        let cd = min(max(d, AnalyticsExportMaze.minDimension), AnalyticsExportMaze.maxDimension)
        masterMaze = LEMACEngineASH.generateCubic(cw, ch, cd)
        masterMazeWidth = cw; masterMazeHeight = ch; masterMazeDepth = cd
        masterMazeId = "live-\(Int(Date().timeIntervalSince1970))"
    }

    // MARK: — Shared config (this is what makes it "always running" across sessions/devices)

    private func refreshFromRemote() async {
        guard let obj = await AutumnGASClient.shared.ashread(path: configPath) as? [String: Any] else {
            // TF164: genuinely no config exists yet anywhere (confirmed
            // directly — the whole ashtree/analytics-live/ directory was
            // 404). Rather than sit at the local default forever waiting
            // for an admin to press a button, the first session to ever
            // see this initializes it live and writes the config itself —
            // "should already be toggled on," including for the very
            // first person, ever.
            guard !didInitializeRemote else { return }
            didInitializeRemote = true
            if masterMaze == nil { generateMasterMaze(width: masterMazeWidth, height: masterMazeHeight, depth: masterMazeDepth) }
            isEnabled = true
            await writeConfig()
            return
        }
        didInitializeRemote = true
        let withinSettleWindow = lastLocalWriteTime.map { Date().timeIntervalSince($0) < writeSettleWindow } ?? false
        if !withinSettleWindow {
            isEnabled = (obj["enabled"] as? Bool) ?? true
            currentChunkIndex = (obj["currentChunkIndex"] as? Int) ?? currentChunkIndex
        }
        masterMazeId = (obj["mazeId"] as? String) ?? masterMazeId
        masterMazeWidth = (obj["width"] as? Int) ?? masterMazeWidth
        masterMazeHeight = (obj["height"] as? Int) ?? masterMazeHeight
        masterMazeDepth = (obj["depth"] as? Int) ?? masterMazeDepth
        // TF161: resumability — if this device doesn't have the master
        // maze's actual structure yet (fresh launch, or the flag was
        // enabled by someone else), regenerate it from the SAME stored
        // seed data so every contributing session nests events into an
        // identical structure, not independently-generated mazes that
        // happen to share dimensions.
        if masterMaze == nil, !masterMazeId.isEmpty,
           let gridDict = obj["grid"] as? [String: Any],
           let gridData = try? JSONSerialization.data(withJSONObject: gridDict),
           let cubic = try? JSONDecoder().decode(LEMACEngineASH.CubicResult.self, from: gridData) {
            masterMaze = cubic
        }
    }

    private func writeConfig() async {
        lastLocalWriteTime = Date()
        var payload: [String: Any] = [
            "enabled": isEnabled,
            "mazeId": masterMazeId,
            "currentChunkIndex": currentChunkIndex,
            "width": masterMazeWidth, "height": masterMazeHeight, "depth": masterMazeDepth
        ]
        if let masterMaze, let data = try? JSONEncoder().encode(masterMaze),
           let dict = try? JSONSerialization.jsonObject(with: data) as? [String: Any] {
            payload["grid"] = dict
        }
        let ok = await AutumnGASClient.shared.ashwriteReplace(path: configPath, uid: "live-feed", payload: payload, message: "live feed config update")
        // TF164: the GAS wrapper always reports {ok: true} regardless of
        // whether the underlying GitHub write actually landed (a real bug
        // in presence.gs, not something fixable from here) — so this
        // return value can't be fully trusted either. Logged into
        // statusText anyway since it's at least sometimes accurate (a
        // genuine network failure on this device's own request still
        // surfaces), and it's better than reporting nothing.
        if !ok { statusText = "config write reported failure" }
    }

    // MARK: — Chunked writes

    private func subscribeToAnalyticsEvents() {
        // Piggybacks on the exact same events AnalyticsEventLogger already
        // captures (chat reflexes, aircraft/satellite/vessel batches,
        // presence) — the live feed and the manual per-session log are two
        // independent consumers of the same real activity, not two
        // separate collection mechanisms to maintain.
        let nc = NotificationCenter.default
        for name in [ReflexActivityBus.notificationName, ReflexActivityBus.toolNotificationName,
                     ReflexActivityBus.mathOpNotificationName, ReflexActivityBus.emotionNotificationName,
                     ReflexActivityBus.realTimeFeedNotificationName, ReflexActivityBus.presenceNotificationName] {
            observers.append(nc.addObserver(forName: name, object: nil, queue: nil) { [weak self] note in
                Task { @MainActor in self?.handleEvent(name: name, userInfo: note.userInfo) }
            })
        }
    }

    private func handleEvent(name: Notification.Name, userInfo: [AnyHashable: Any]?) {
        guard isEnabled, masterMaze != nil else { return }
        var entry: [String: Any] = ["ts": ISO8601DateFormatter().string(from: Date())]
        switch name {
        case ReflexActivityBus.notificationName:
            guard let s = userInfo?["stage"] as? String else { return }
            entry["category"] = "stage"; entry["label"] = s
        case ReflexActivityBus.toolNotificationName:
            guard let t = userInfo?["tool"] as? String else { return }
            entry["category"] = "tool"; entry["label"] = t
        case ReflexActivityBus.mathOpNotificationName:
            guard let o = userInfo?["op"] as? String else { return }
            entry["category"] = "math"; entry["label"] = o
        case ReflexActivityBus.emotionNotificationName:
            guard let e = userInfo?["emotion"] as? String else { return }
            entry["category"] = "emotion"; entry["label"] = e
        case ReflexActivityBus.realTimeFeedNotificationName:
            guard let k = userInfo?["kind"] as? String, let c = userInfo?["count"] as? Int else { return }
            entry["category"] = "realtime_feed"; entry["label"] = k; entry["detail"] = "\(c)"
        case ReflexActivityBus.presenceNotificationName:
            guard let c = userInfo?["connectedCount"] as? Int else { return }
            entry["category"] = "presence"; entry["label"] = "connected_users"; entry["detail"] = "\(c)"
        default: return
        }
        pendingChunkEvents.append(entry)
        // TF164: no longer flushes immediately per event — the flushTimer
        // above now batches these, which is the actual fix for the rapid-
        // successive-writes problem.
    }

    /// Writes accumulated events to the current chunk file, and — TF161's
    /// actual 5MB-cap behavior — closes it and starts a new one under the
    /// same master maze the instant the running size would exceed the cap,
    /// rather than letting one file grow past it.
    private func flushIfNeeded() async {
        guard !pendingChunkEvents.isEmpty else { return }
        let batch = pendingChunkEvents
        pendingChunkEvents = []
        guard let data = try? JSONSerialization.data(withJSONObject: batch) else { return }
        let projectedBytes = currentChunkBytes + data.count
        if projectedBytes > chunkCapBytes && currentChunkBytes > 0 {
            currentChunkIndex += 1
            currentChunkBytes = 0
            await writeConfig()
        }
        let path = chunkPath(index: currentChunkIndex)
        let ok = await AutumnGASClient.shared.ashwrite(path: path, uid: "live-feed", append: true, payload: batch)
        if ok {
            currentChunkBytes += data.count
            statusText = "chunk \(currentChunkIndex), \(currentChunkBytes / 1024) KB"
            recentLiveEvents.append(contentsOf: batch)
            if recentLiveEvents.count > 4000 { recentLiveEvents.removeFirst(recentLiveEvents.count - 4000) }
            await writeLiveExport()
        } else {
            // TF161: resilience — if the write genuinely failed (a real
            // GitHub/GAS error, not just this call's own retry), put the
            // batch back so the next successful flush picks it back up
            // rather than silently losing it.
            pendingChunkEvents = batch + pendingChunkEvents
            statusText = "write failed, will retry"
        }
    }

    // MARK: — Live preview export for the web viewer
    //
    // TF163: found the real viewer repo (Ariel/session-cube-src) and
    // confirmed its RawExport TypeScript type directly — it matches this
    // app's own export JSON almost field-for-field, independently arrived
    // at without ever having seen that file. Rather than duplicate the
    // web viewer's maze-solving/path logic in TypeScript, this keeps the
    // one real nesting implementation on the Swift side (already built,
    // already verified via CI) and just periodically writes a ready-to-
    // load RawExport-shaped file the viewer can fetch directly, the same
    // way it already loads any other file — no second pipeline on the web
    // side to maintain. This is deliberately a simpler, single-layer
    // distribution for a live "what's happening right now" preview; the
    // fuller grouped-by-type, multi-layer version stays exactly what the
    // manual/live EXPORT button in the admin panel produces for real
    // archival use.
    private var recentLiveEvents: [[String: Any]] = []

    private func writeLiveExport() async {
        guard let cubic = masterMaze else { return }
        let solution = LEMACEngineASH.solveCubic(cubic)
        guard !solution.isEmpty else { return }
        var buckets: [[[String: Any]]] = Array(repeating: [], count: solution.count)
        for (i, event) in recentLiveEvents.enumerated() {
            buckets[min(i * solution.count / max(recentLiveEvents.count, 1), solution.count - 1)].append(event)
        }
        var pathJSON: [[String: Any]] = []
        for (i, pt) in solution.enumerated() {
            pathJSON.append(["order": i, "x": pt.x, "y": pt.y, "z": pt.z, "events": buckets[i]])
        }
        var cubeCells: [[String: Any]] = []
        for z in 0..<masterMazeDepth {
            for y in 0..<masterMazeHeight {
                for x in 0..<masterMazeWidth {
                    let c = cubic.grid[z][y][x]
                    cubeCells.append(["x": x, "y": y, "z": z, "walls": ["top": c.top, "bottom": c.bottom, "left": c.left, "right": c.right, "front": c.front, "back": c.back]])
                }
            }
        }
        func openingJSON(_ p: LEMACEngineASH.Perimeter3D) -> [String: Any] { ["x": p.x, "y": p.y, "z": p.z, "face": p.face] }
        let root: [String: Any] = [
            "exportedAt": ISO8601DateFormatter().string(from: Date()),
            "mode": "LIVE FEED",
            "cube": [
                "width": masterMazeWidth, "height": masterMazeHeight, "depth": masterMazeDepth,
                "entrance": openingJSON(cubic.start), "exit": openingJSON(cubic.end),
                "cells": cubeCells
            ],
            "pathIndex": [["layer": 0, "path": pathJSON]],
            "totalEvents": recentLiveEvents.count
        ]
        guard JSONSerialization.isValidJSONObject(root) else { return }
        _ = await AutumnGASClient.shared.ashwriteReplace(
            path: "ashtree/analytics-live/\(masterMazeId)/latest-export.json",
            uid: "live-feed", payload: root, message: "live export refresh"
        )
    }

    private func chunkPath(index: Int) -> String {
        "ashtree/analytics-live/\(masterMazeId)/chunk-\(index).json"
    }

    /// All chunk paths for the CURRENT master maze — used by the export
    /// panel's "compile the live feed" path.
    public func allChunkPaths() -> [String] {
        guard !masterMazeId.isEmpty else { return [] }
        return (0...currentChunkIndex).map { chunkPath(index: $0) }
    }

    deinit {
        refreshTimer?.invalidate()
        flushTimer?.invalidate()
        observers.forEach { NotificationCenter.default.removeObserver($0) }
    }
}
