import Foundation
import LEATRCore
import AutumnServices

/// TF161: the live feed is a genuinely separate concern from the manual
/// export built earlier — its own master maze, its own chunked directory,
/// and (this is the real constraint worth being upfront about) no
/// server-side always-on process exists here, because there isn't one:
/// the data itself only ever gets generated by whichever device's app is
/// actually open and processing reflexes. "Always running" in practice
/// means every active session checks a shared, GAS-persisted flag and
/// contributes to the same chunk stream when it's on — matching exactly
/// what was described: if nobody has the app open, there's genuinely
/// nothing to collect, and the first person who signs in makes the
/// journal active again.
@MainActor
public final class LiveFeedController: ObservableObject {
    public static let shared = LiveFeedController()

    @Published public private(set) var isEnabled = false
    @Published public private(set) var masterMaze: LEMACEngineASH.CubicResult?
    @Published public private(set) var masterMazeWidth = 10
    @Published public private(set) var masterMazeHeight = 10
    @Published public private(set) var masterMazeDepth = 10
    @Published public private(set) var masterMazeId: String = ""
    @Published public private(set) var currentChunkIndex = 0
    @Published public private(set) var currentChunkBytes = 0
    @Published public var statusText = ""

    private let chunkCapBytes = 5 * 1024 * 1024   // 5 MB per chunk, per direct spec
    private let configPath = "ashtree/analytics-live/config.json"
    private var pendingChunkEvents: [[String: Any]] = []
    private var refreshTimer: Timer?
    // TF162: the actual bug behind "toggles itself off after a while."
    // GitHub's Contents API (what ashread/ashwrite go through) has real
    // write-propagation lag — a stale read shortly after a write is a
    // pattern already confirmed elsewhere in this exact codebase, not a
    // one-off guess. The 30s poll was applying every remote read
    // unconditionally, so a stale "enabled: false" read shortly after
    // toggling on would silently overwrite the local state back off. This
    // tracks the last local write and skips applying a remote read for a
    // window afterward, giving the write time to actually propagate before
    // a poll is trusted again.
    private var lastLocalWriteTime: Date?
    private let writeSettleWindow: TimeInterval = 90
    private var observers: [NSObjectProtocol] = []

    private init() {
        Task { await refreshFromRemote() }
        // Poll the shared flag periodically rather than only on launch —
        // any session should pick up an admin's toggle without needing a
        // relaunch.
        refreshTimer = Timer.scheduledTimer(withTimeInterval: 30, repeats: true) { [weak self] _ in
            Task { await self?.refreshFromRemote() }
        }
        subscribeToAnalyticsEvents()
    }

    // MARK: — Admin control (the toggle in AnalyticsExportPanel)

    /// Turning this on for the first time generates the master maze and
    /// writes the shared config; turning it off just flips the flag —
    /// the master maze and whatever's already been chunked stay exactly
    /// where they are, ready to resume the moment it's re-enabled.
    public func setEnabled(_ on: Bool) async {
        if on && masterMaze == nil {
            generateMasterMaze(width: masterMazeWidth, height: masterMazeHeight, depth: masterMazeDepth)
        }
        isEnabled = on
        await writeConfig()
    }

    public func regenerateMasterMaze(width: Int, height: Int, depth: Int) async {
        generateMasterMaze(width: width, height: height, depth: depth)
        currentChunkIndex = 0
        currentChunkBytes = 0
        pendingChunkEvents = []
        await writeConfig()
    }

    private func generateMasterMaze(width w: Int, height h: Int, depth d: Int) {
        let cw = min(max(w, AnalyticsExportMaze.minDimension), AnalyticsExportMaze.maxDimension)
        let ch = min(max(h, AnalyticsExportMaze.minDimension), AnalyticsExportMaze.maxDimension)
        let cd = min(max(d, AnalyticsExportMaze.minDimension), AnalyticsExportMaze.maxDimension)
        masterMaze = LEMACEngineASH.generateCubic(cw, ch, cd)
        masterMazeWidth = cw; masterMazeHeight = ch; masterMazeDepth = cd
        masterMazeId = "live-\(Int(Date().timeIntervalSince1970))"
    }

    // MARK: — Shared config (this is what makes it "always running" across sessions/devices)

    private func refreshFromRemote() async {
        guard let obj = await AutumnGASClient.shared.ashread(path: configPath) as? [String: Any] else { return }
        // TF162: within the settle window after our OWN write, a remote
        // read is more likely to be a stale echo of the pre-write state
        // than genuinely newer information — skip applying it rather than
        // let it silently undo what was just set locally. Structural
        // fields (maze dimensions/grid) are still safe to pick up even
        // during the window, since those don't change from a plain on/off
        // toggle; only `enabled` and the chunk index (which this device's
        // own writes also drive) are held back.
        let withinSettleWindow = lastLocalWriteTime.map { Date().timeIntervalSince($0) < writeSettleWindow } ?? false
        if !withinSettleWindow {
            isEnabled = (obj["enabled"] as? Bool) ?? false
            currentChunkIndex = (obj["currentChunkIndex"] as? Int) ?? currentChunkIndex
        }
        masterMazeId = (obj["mazeId"] as? String) ?? masterMazeId
        masterMazeWidth = (obj["width"] as? Int) ?? masterMazeWidth
        masterMazeHeight = (obj["height"] as? Int) ?? masterMazeHeight
        masterMazeDepth = (obj["depth"] as? Int) ?? masterMazeDepth
        // TF161: resumability — if this device doesn't have the master
        // maze's actual structure yet (fresh launch, or the flag was
        // enabled by someone else), regenerate it from the SAME stored
        // seed data so every contributing session nests events into an
        // identical structure, not independently-generated mazes that
        // happen to share dimensions.
        if masterMaze == nil, !masterMazeId.isEmpty,
           let gridDict = obj["grid"] as? [String: Any],
           let gridData = try? JSONSerialization.data(withJSONObject: gridDict),
           let cubic = try? JSONDecoder().decode(LEMACEngineASH.CubicResult.self, from: gridData) {
            masterMaze = cubic
        }
    }

    private func writeConfig() async {
        lastLocalWriteTime = Date()
        var payload: [String: Any] = [
            "enabled": isEnabled,
            "mazeId": masterMazeId,
            "currentChunkIndex": currentChunkIndex,
            "width": masterMazeWidth, "height": masterMazeHeight, "depth": masterMazeDepth
        ]
        if let masterMaze, let data = try? JSONEncoder().encode(masterMaze),
           let dict = try? JSONSerialization.jsonObject(with: data) as? [String: Any] {
            payload["grid"] = dict
        }
        _ = await AutumnGASClient.shared.ashwriteReplace(path: configPath, uid: "live-feed", payload: payload, message: "live feed config update")
    }

    // MARK: — Chunked writes

    private func subscribeToAnalyticsEvents() {
        // Piggybacks on the exact same events AnalyticsEventLogger already
        // captures (chat reflexes, aircraft/satellite/vessel batches,
        // presence) — the live feed and the manual per-session log are two
        // independent consumers of the same real activity, not two
        // separate collection mechanisms to maintain.
        let nc = NotificationCenter.default
        for name in [ReflexActivityBus.notificationName, ReflexActivityBus.toolNotificationName,
                     ReflexActivityBus.mathOpNotificationName, ReflexActivityBus.emotionNotificationName,
                     ReflexActivityBus.realTimeFeedNotificationName, ReflexActivityBus.presenceNotificationName] {
            observers.append(nc.addObserver(forName: name, object: nil, queue: nil) { [weak self] note in
                Task { @MainActor in self?.handleEvent(name: name, userInfo: note.userInfo) }
            })
        }
    }

    private func handleEvent(name: Notification.Name, userInfo: [AnyHashable: Any]?) {
        guard isEnabled, masterMaze != nil else { return }
        var entry: [String: Any] = ["ts": ISO8601DateFormatter().string(from: Date())]
        switch name {
        case ReflexActivityBus.notificationName:
            guard let s = userInfo?["stage"] as? String else { return }
            entry["category"] = "stage"; entry["label"] = s
        case ReflexActivityBus.toolNotificationName:
            guard let t = userInfo?["tool"] as? String else { return }
            entry["category"] = "tool"; entry["label"] = t
        case ReflexActivityBus.mathOpNotificationName:
            guard let o = userInfo?["op"] as? String else { return }
            entry["category"] = "math"; entry["label"] = o
        case ReflexActivityBus.emotionNotificationName:
            guard let e = userInfo?["emotion"] as? String else { return }
            entry["category"] = "emotion"; entry["label"] = e
        case ReflexActivityBus.realTimeFeedNotificationName:
            guard let k = userInfo?["kind"] as? String, let c = userInfo?["count"] as? Int else { return }
            entry["category"] = "realtime_feed"; entry["label"] = k; entry["detail"] = "\(c)"
        case ReflexActivityBus.presenceNotificationName:
            guard let c = userInfo?["connectedCount"] as? Int else { return }
            entry["category"] = "presence"; entry["label"] = "connected_users"; entry["detail"] = "\(c)"
        default: return
        }
        pendingChunkEvents.append(entry)
        Task { await flushIfNeeded() }
    }

    /// Writes accumulated events to the current chunk file, and — TF161's
    /// actual 5MB-cap behavior — closes it and starts a new one under the
    /// same master maze the instant the running size would exceed the cap,
    /// rather than letting one file grow past it.
    private func flushIfNeeded() async {
        guard !pendingChunkEvents.isEmpty else { return }
        let batch = pendingChunkEvents
        pendingChunkEvents = []
        guard let data = try? JSONSerialization.data(withJSONObject: batch) else { return }
        let projectedBytes = currentChunkBytes + data.count
        if projectedBytes > chunkCapBytes && currentChunkBytes > 0 {
            currentChunkIndex += 1
            currentChunkBytes = 0
            await writeConfig()
        }
        let path = chunkPath(index: currentChunkIndex)
        let ok = await AutumnGASClient.shared.ashwrite(path: path, uid: "live-feed", append: true, payload: batch)
        if ok {
            currentChunkBytes += data.count
            statusText = "chunk \(currentChunkIndex), \(currentChunkBytes / 1024) KB"
            recentLiveEvents.append(contentsOf: batch)
            if recentLiveEvents.count > 4000 { recentLiveEvents.removeFirst(recentLiveEvents.count - 4000) }
            await writeLiveExport()
        } else {
            // TF161: resilience — if the write genuinely failed (a real
            // GitHub/GAS error, not just this call's own retry), put the
            // batch back so the next successful flush picks it back up
            // rather than silently losing it.
            pendingChunkEvents = batch + pendingChunkEvents
            statusText = "write failed, will retry"
        }
    }

    // MARK: — Live preview export for the web viewer
    //
    // TF163: found the real viewer repo (Ariel/session-cube-src) and
    // confirmed its RawExport TypeScript type directly — it matches this
    // app's own export JSON almost field-for-field, independently arrived
    // at without ever having seen that file. Rather than duplicate the
    // web viewer's maze-solving/path logic in TypeScript, this keeps the
    // one real nesting implementation on the Swift side (already built,
    // already verified via CI) and just periodically writes a ready-to-
    // load RawExport-shaped file the viewer can fetch directly, the same
    // way it already loads any other file — no second pipeline on the web
    // side to maintain. This is deliberately a simpler, single-layer
    // distribution for a live "what's happening right now" preview; the
    // fuller grouped-by-type, multi-layer version stays exactly what the
    // manual/live EXPORT button in the admin panel produces for real
    // archival use.
    private var recentLiveEvents: [[String: Any]] = []

    private func writeLiveExport() async {
        guard let cubic = masterMaze else { return }
        let solution = LEMACEngineASH.solveCubic(cubic)
        guard !solution.isEmpty else { return }
        var buckets: [[[String: Any]]] = Array(repeating: [], count: solution.count)
        for (i, event) in recentLiveEvents.enumerated() {
            buckets[min(i * solution.count / max(recentLiveEvents.count, 1), solution.count - 1)].append(event)
        }
        var pathJSON: [[String: Any]] = []
        for (i, pt) in solution.enumerated() {
            pathJSON.append(["order": i, "x": pt.x, "y": pt.y, "z": pt.z, "events": buckets[i]])
        }
        var cubeCells: [[String: Any]] = []
        for z in 0..<masterMazeDepth {
            for y in 0..<masterMazeHeight {
                for x in 0..<masterMazeWidth {
                    let c = cubic.grid[z][y][x]
                    cubeCells.append(["x": x, "y": y, "z": z, "walls": ["top": c.top, "bottom": c.bottom, "left": c.left, "right": c.right, "front": c.front, "back": c.back]])
                }
            }
        }
        func openingJSON(_ p: LEMACEngineASH.Perimeter3D) -> [String: Any] { ["x": p.x, "y": p.y, "z": p.z, "face": p.face] }
        let root: [String: Any] = [
            "exportedAt": ISO8601DateFormatter().string(from: Date()),
            "mode": "LIVE FEED",
            "cube": [
                "width": masterMazeWidth, "height": masterMazeHeight, "depth": masterMazeDepth,
                "entrance": openingJSON(cubic.start), "exit": openingJSON(cubic.end),
                "cells": cubeCells
            ],
            "pathIndex": [["layer": 0, "path": pathJSON]],
            "totalEvents": recentLiveEvents.count
        ]
        guard JSONSerialization.isValidJSONObject(root) else { return }
        _ = await AutumnGASClient.shared.ashwriteReplace(
            path: "ashtree/analytics-live/\(masterMazeId)/latest-export.json",
            uid: "live-feed", payload: root, message: "live export refresh"
        )
    }

    private func chunkPath(index: Int) -> String {
        "ashtree/analytics-live/\(masterMazeId)/chunk-\(index).json"
    }

    /// All chunk paths for the CURRENT master maze — used by the export
    /// panel's "compile the live feed" path.
    public func allChunkPaths() -> [String] {
        guard !masterMazeId.isEmpty else { return [] }
        return (0...currentChunkIndex).map { chunkPath(index: $0) }
    }

    deinit {
        refreshTimer?.invalidate()
        observers.forEach { NotificationCenter.default.removeObserver($0) }
    }
}
