default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "P6Z72KS63T",
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: "#{ENV["HOME"]}/.appstoreconnect/private_keys/AuthKey_P6Z72KS63T.p8"
    )

    increment_build_number(
      build_number: Time.now.strftime("%Y%m%d%H%M")
    )

    build_app(
      scheme: "AutumnApp",
      export_method: "app-store",
      export_options: {
        signingStyle: "automatic",
        teamID: "L7AHWS9Q6V"
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
